### ISSUE TITLE
Switch to use ProducesResponseType instead of SwaggerResponse

### ISSUE THREAD

**Issue by CodeStoneK** [mattfrear/Swashbuckle.AspNetCore.Examples#30]
Swashbuckkle.AspNetCore has moved away from **SwaggerResponse** annotation. As described 
[here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/3562d67e5eab8b22b35c536176645e90008f1f1d/README.md#include-descriptions-from-xml-comments), we should be using **ProducesResponseType** instead, which I think is a cleaner approach as it removes the direct dependency of the API dll on Swashbuckle. I am wondering if/when this will be incorporated in here. Thanks.

**Comment by mattfrear** [comment]
You can use `ProducesResponseType` if you like, this library works fine with it. I confess I'd never tried it until now.

```
[ProducesResponseType(typeof(PersonResponse), 200)]
[SwaggerResponseExample(200, typeof(PersonResponseExample))]
[SwaggerRequestExample(typeof(PersonRequest), typeof(PersonRequestExample), jsonConverter: typeof(StringEnumConverter))]
public PersonResponse GetPerson([FromBody]PersonRequest personRequest)
{
```

I prefer the old `SwaggerResponse` notation because you can pass it a description:

![image](https://user-images.githubusercontent.com/169179/35403799-c90d63fa-01f8-11e8-9dca-3fb8b6b5e50a.png)
