### ISSUE TITLE
Not possible to create request examples for certain data types?

### ISSUE THREAD

**Issue by SharlatanY** [mattfrear/Swashbuckle.AspNetCore.Examples#39]
Isn't it possible to create request examples for certain types of body content? What I would like to create a request example for a controller method with the following signature:

```csharp
[SwaggerRequestExample(typeof(Dictionary<string, object>), typeof(TestExampleDict))]
public async Task<IActionResult> TestMethod([FromBody]Dictionary<string, object> dictionary)
```

With an example class like this:
```csharp
public class TestExampleDict : IExamplesProvider
{
    public object GetExamples()
    {
        return new Dictionary<string, object>
        {
            {"key1", 1 },
            {"key2", "string" },
            {"key3", true }
        };
    }
}
```

Th example just doesn't get created and when debugging, the _GetExamples()_ method is never called.
Also, if I look at the generated JSON file, the examples for this type aren't listed.

I know that examples work per se in my project because I have some other controller methods where custom data types are passed in wih [FromBody] and my request examples for those methods work without a problem.

I also tried a few other things like not using type "object" or "Dictionary", etc but nothing worked.

**Here's the alternatives I tried but where the request example didn't work as well:**

- Using Dictionary<string, string> instead of Dictionary<string, object>
- Using Tuple<string, object> instead of Dictionary<string, object>
- Using Tuple<string, string> instead of Dictionary<string, object>
- Deriving my own type from Dictionary and using this as [FromBody] parameter: public class CustomDict : Dictionary<string, object>
```csharp
//in seperate CustomDict.cs file
public class CustomDict : Dictionary<string, object> { }
..
//controller method in controller class
public async Task<IActionResult> TestMethod([FromBody]CustomDict dictionary)
```

**The only thing that worked so far is wrapping the dictionary within a container class. In that case the example request works without a problem**
Container class example:
```csharp
public class DictionaryContainer
{
    public Dictionary<string, object> Dict;
}
```
ExampleProvider example:
```csharp
public class TestExample: IExamplesProvider
{
    public object GetExamples()
    {
        var dict = new Dictionary<string, object>
        {
            {"IntVal", 13},
            {"BoolVal", true},
            {"GuidVal", Guid.Parse("1a0bdb34-a56a-439b-a8e6-6abd684dc817")}
        };

        return new DictionaryContainer {Dict = dict};
    }
}
```
Method signature example:
```csharp
[SwaggerRequestExample(typeof(DictionaryContainer), typeof(TestExample))]
public async Task<IActionResult> TestMethod([FromBody]DictionaryContainer dictContainer)
```
In this case, the request example is generated and displayed without a problem. But although I can live with this workaround if I absolutely have too, I'd rather not because it's a bit ugly and makes the body content clients have to send unnecessarily complex. In this example
```json
{
  "Dict": {
    "IntVal": 13,
    "BoolVal": true,
    "GuidVal": "1a0bdb34-a56a-439b-a8e6-6abd684dc817"
  }
}
```
Instead of just
```json
{
  "IntVal": 13,
  "BoolVal": true,
  "GuidVal": "1a0bdb34-a56a-439b-a8e6-6abd684dc817"
}
```

**So, I guess, my question is**: 
Am I doing something wrong? Or is there no native support for creating request examples for this kind of data type? If the latter's the case, is there any kind of workaround where I could get a simple body structure like the following and still use request examples?:
 ```json
{
  "IntVal": 13,
  "BoolVal": true,
  "GuidVal": "1a0bdb34-a56a-439b-a8e6-6abd684dc817"
}
```

Thanks a lot in advance!

**Comment by mattfrear** [comment]
Hi Sharlatan,
Firstly thanks for a detailed and nicely formatted comment! I admire your persistence and trial and error in trying to get it to work.

Before I investigate further, have you checked the [Known Issues](https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples#known-issues) section of the readme? Could any of these issues apply in your case?

If it's not a Known Issue, then maybe could I suggest you download the source code of this project and reproduce your issue in my WebApi project? Because that will be the first thing I will try to do.

Otherwise, I will investigate it for you when I get a chance, possibly some time in the next week or so.

**Comment by mattfrear** [comment]
FWIW, personally I almost always use custom classes in my API design for requests and responses which is why I haven't seen your issue. But there was an issue that someone reported a while ago when trying to use `List<T>` in a request, so I coded a fix for that. See [list request examples](https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples#list-request-examples) in the Readme.

**Comment by SharlatanY** [comment]
Hi Matt,

Thanks for getting back to me so quickly! I'll give your suggestions a try and share my findings. Probably won't find the time today, though.

All I can say for now is, that there doesn't seem to be a known issue that seems likely to be related to my problem. But considering this listed limitation:

> For requests, in the Swagger 2.0 spec there is only one schema for each request object defined across all the API endpoints. 

, we'll probably have to use a custom class some when in the future and I feel we should do that rather sooner  than later and this issue won't be a problem for us anymore anyway (will have to discuss this internally first but, to me at least, it would make sense).

Until then and thanks again!

**Comment by antonGritsenko** [comment]
It can be reproduced based on Swashbuckle.AspNetCore.Examples. Just change
`public class PersonRequest `
to
`public class PersonRequest : Dictionary<string, object>`
in \test\WebApi\Models\PersonRequest.cs
and Swagger will not able to show example for /api/Values/api/values/person

**Comment by mattfrear** [comment]
Cool, Maybe you could figure out a code fix and submit a PR?

**Comment by antonGritsenko** [comment]
@mattfrear this project is new for me, so hard to find something specific. But from first look, it somewhere in Schema class (or ISchemaRegistry). Because this how Refs parameters of Schema isntance look for original PersonRequest class:

> #/definitions/PersonRequest

But if I add _: Dictionary<string, object>_ then Refs just null.
**#/definitions** looks like JSON schema, and it has a LOT of known problem with different types.

May be you can point where to looks next?

**Comment by antonGritsenko** [comment]
Hm, I think I have found workaround, but need your help. Class ExamplesOperationFilter, method SetRequestModelExamples, you have comment:
`// var name = attr.RequestType.Name; // this doesn't work for generic types, so need to to schema.ref split`
What does "doesn't work" actually mean?

**Comment by mattfrear** [comment]
I've just had a play, and there's no way for this to work. Let me explain why.

When you have a controller action like:
```csharp
        [HttpPost]
        [Route("api/values/person")]
        public PersonResponse GetPerson([FromBody]PersonRequest personRequest)
        {
```
Then Swashbuckle generates an api path definition like this in the swagger.json:
```json
		"/api/Values/person": {
			"post": {
				"tags": ["Values"],
				"summary": " (Auth)",
				"operationId": "ApiValuesPost",
				"consumes": ["application/json", "text/json", "application/json-patch+json"],
				"produces": ["text/plain", "application/json", "text/json"],
				"parameters": [{
						"name": "personRequest",
						"in": "body",
						"required": false,
						"schema": {
							"$ref": "#/definitions/PersonRequest"
						}
					}
```
Notice the `"$ref": "#/definitions/PersonRequest`. If you then scroll to the end of the swagger.json, you'll see:
```json
	"definitions": {
		"PersonRequest": {
			"type": "object",
			"properties": {
				"title": {
					"enum": ["None", "Dr", "Miss", "Mr", "Mrs", "Ms"],
					"type": "string"
				},
				"age": {
					"format": "int32",
					"type": "integer"
				},
				"firstName": {
					"description": "The first name of the person",
					"type": "string"
				},
				"income": {
					"format": "double",
					"type": "number"
				}
			},
		},
```

If you then add a SwaggerRequestExample attribute from my project to your controller, i.e. 
```csharp
[SwaggerRequestExample(typeof(PersonRequest), typeof(PersonRequestExample))]
```
Then the PersonRequest "definition" in the swagger.json gets an example added:
```json
	"definitions": {
		"PersonRequest": {
			"type": "object",
			"properties": {
				"title": {
					"enum": ["None", "Dr", "Miss", "Mr", "Mrs", "Ms"],
					"type": "string"
				},
				"age": {
					"format": "int32",
					"type": "integer"
				},
				"firstName": {
					"description": "The first name of the person",
					"type": "string"
				},
				"income": {
					"format": "double",
					"type": "number"
				}
			},
			"example": {
				"title": "Mr",
				"age": 24,
				"firstName": "Dave"
			}
		},
```
Now, when you use a Dictionary<> in your request, ala:
```csharp
        public IEnumerable<PersonResponse> GetPersonDictionary([FromBody]Dictionary<string, object> dictionaryRequest)
        {
```
The api path in swagger.json looks like:
```json
		"/api/values/dictionaryperson": {
			"post": {
				"tags": ["Values"],
				"summary": " (Auth)",
				"operationId": "ApiValuesApiValuesDictionarypersonPost",
				"consumes": ["application/json", "text/json", "application/json-patch+json"],
				"produces": ["text/plain", "application/json", "text/json"],
				"parameters": [{
						"name": "dictionaryRequest",
						"in": "body",
						"required": false,
						"schema": {
							"type": "object",
							"additionalProperties": {
								"type": "object"
							}
						}
					}, 
```
Notice that there's no $ref defined, as Swashbuckle determines that the type for a Dictionary<> is "object". I thought this might be a bug with Swashbuckle, but apparently that is as per the swagger spec. See https://github.com/domaindrivendev/Swashbuckle/issues/844

Since there is no $ref defined, there's no "definition" for my library to add an example to.

**Comment by antonGritsenko** [comment]
@mattfrear yeah, I realized the same as you can see from referenced issue from Swashbuckle. 

PS JsonSchema is really bad thing ((

**Comment by antonGritsenko** [comment]
@mattfrear actually it shouldn't be closed, because initial question was about Dictionary itself.

**Comment by mattfrear** [comment]
@antonGritsenko yes, and in my detailed comment yesterday I attempted to use a Dictionary, which doesn't work, because of Swagger / Swashbuckle limitations.
```
public IEnumerable<PersonResponse> GetPersonDictionary([FromBody]Dictionary<string, object> dictionaryRequest)
```
Therefore the issue is closed.

**Comment by antonGritsenko** [comment]
@mattfrear but take a look on this comment https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/675#issuecomment-379824902

> However, SB will describe it as just that - an open JSON object, with no indication of expected properties
I think here the behavior of Swashbuckle.AspNetCore.Examples is not expected, as it should show something, just regular JSON object from Dictionary.

**Comment by mattfrear** [comment]
I don't know how I can make it any clearer than the very detailed explanation I provided yesterday. There is no schema.$ref defined when Swashbuckle is given a Dictionary, therefore, as per the Swagger spec, there's nowhere for me to add an example.

For me to be able to do anything, Swashbuckle would need to change the way it handles `Dictionary<T>`, but that's not going to happen because what Swashbuckle does is correct as per the swagger spec.

**Comment by antonGritsenko** [comment]
@mattfrear I think I know how to solve this, will try to create a pull.

**Comment by antonGritsenko** [comment]
@mattfrear here is it https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/pull/40

**Comment by mattfrear** [comment]
Hi @SharlatanY 

Thanks to @antonGritsenko's PR your original request

```csharp
[SwaggerRequestExample(typeof(Dictionary<string, object>), typeof(TestExampleDict))]
public async Task<IActionResult> TestMethod([FromBody]Dictionary<string, object> dictionary)
```
Should now work, as of https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.9.0

**Comment by SharlatanY** [comment]
@mattfrear @antonGritsenko Sorry, somehow missed the notifications and only saw your messages when I went back to this thread. Thanks very much for your hard work and helping me resolve this problem! Works like a charm now :)
